### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by danielo515** [antoinemadec/coc-fzf#10]
Hello.
I noticed that you just rollout some breaking changes. Basically my keymaps stopped working, not big deal, but took a bit to figure it out.
I don't have much experience with vim so, is there a mechanism to notify this breaking changes when you update? Do you plan to introduce more breaking changes?

thanks and regards

**Comment by antoinemadec** [comment]
@danielo515 , the main mechanism is to look at the commit messages.

For instance, on [vim-plug](https://github.com/junegunn/vim-plug), after updating with ```:PlugUpdate```, you can press ```D``` in order to see the changes with their commit messages.
You can also jump into the new commits to see which files were updated.

> Do you plan to introduce more breaking changes?


No, I don't **plan** to, I will try to avoid it :smile:
However if a new feature requires to break something, and if I decide that the benefit of this feature outweigh the drawback of introducing some changes, I will.

Thanks,
Antoine
