### ISSUE TITLE
Getting error CocFzfList symbols

### ISSUE THREAD

**Issue by KirillYatsenko** [antoinemadec/coc-fzf#110]
Hi,

I'm getting python3 error when running command

CocFzfList symbols

![image](https://user-images.githubusercontent.com/14968248/167580539-7603e8ef-8f54-4340-bb3b-a02c1a34d698.png)

**Comment by antoinemadec** [comment]
Could you please fill the template so I can help you ?

**Comment by KirillYatsenko** [comment]
What template? Can you give an example?

**Comment by antoinemadec** [comment]
@KirillYatsenko this is the template that should show up when you create a bug report.
Unless you use some kind of app, you should have seen it. Here it is:

# Environment
  - ```echo $FZF_DEFAULT_OPTS```:
  - ```bat --version```:
  - Are your vim plugins up-to-date?:
  - ```(n)vim --version```:
```
(n)vim --version output
```

# Describe the Bug
A clear and concise description of what the bug is.
You can also include screenshots if needed.

# To Reproduce
## **Minimal** vimrc
```vim
" minimal vimrc
```

## Steps to Reproduce
1. nvim -u minimal_vimrc
2. ```:e myfile.py```
3. etc

# Expected Behavior
A clear and concise description of what you expected to happen.

**Comment by antoinemadec** [comment]
@KirillYatsenko do you have any news about this?
I will close this ticket in a couple of days if I don't have any news from you.

**Comment by antoinemadec** [comment]
Everything works fine on my end. Don't hesitate to reopen a ticket with a filled template.
#ghosted
